# Generated by Django 5.2.17 on 2026-08-09 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DISTANCE', 'Distance'), ('AREA', 'Area')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('coordinates', models.JSONField()),
                ('calculated_value', models.DecimalField(db_column='calculated_value', decimal_places=8, max_digits=20)),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements_created', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='surveys.survey')),
            ],
            options={
                'db_table': 'measurement',
                'indexes': [models.Index(fields=['survey'], name='measurement_survey__c71de9_idx'), models.Index(fields=['type'], name='measurement_type_d3c473_idx')],
            },
        ),
    ]
