# Generated by Django 5.2.17 on 2026-08-09 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, db_column='submitted_at', null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='approved_at', null=True)),
                ('rejection_reason', models.TextField(blank=True, db_column='rejection_reason', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_approved', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_submitted', to=settings.AUTH_USER_MODEL)),
                ('survey', models.OneToOneField(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='surveys.survey')),
            ],
            options={
                'db_table': 'approval',
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(db_column='approval_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='approvals.approval')),
            ],
            options={
                'db_table': 'approval_history',
                'indexes': [models.Index(fields=['approval'], name='approval_hi_approva_3c0d6a_idx'), models.Index(fields=['actor'], name='approval_hi_actor_i_730299_idx')],
            },
        ),
    ]
