# Generated by Django 5.2.17 on 2026-08-09 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('survey_date', models.DateField(db_column='survey_date')),
                ('drone_model', models.CharField(blank=True, db_column='drone_model', max_length=255, null=True)),
                ('pilot', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinate_reference_system', models.CharField(db_column='coordinate_reference_system', default='EPSG:4326', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('processing_status', models.CharField(db_column='processing_status', default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='projects.project')),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='projects.site')),
            ],
            options={
                'db_table': 'survey',
                'indexes': [models.Index(fields=['project'], name='survey_project_e1bcf0_idx'), models.Index(fields=['site'], name='survey_site_id_650808_idx'), models.Index(fields=['status'], name='survey_status_55f281_idx'), models.Index(fields=['survey_date'], name='survey_survey__82bc34_idx')],
            },
        ),
    ]
