# Generated by Django 5.2.17 on 2026-08-09 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_ARCHIVED', 'Project Archived'), ('SITE_CREATED', 'Site Created'), ('SITE_UPDATED', 'Site Updated'), ('SITE_DELETED', 'Site Deleted'), ('SURVEY_CREATED', 'Survey Created'), ('SURVEY_SUBMITTED', 'Survey Submitted'), ('FILE_UPLOADED', 'File Uploaded'), ('FILE_UPLOAD_FAILED', 'File Upload Failed'), ('PROCESSING_STARTED', 'Processing Started'), ('PROCESSING_FAILED', 'Processing Failed'), ('PROCESSING_RETRY', 'Processing Retry'), ('APPROVAL_SUBMITTED', 'Approval Submitted'), ('APPROVAL_APPROVED', 'Approval Approved'), ('APPROVAL_REJECTED', 'Approval Rejected'), ('SURVEY_ARCHIVED', 'Survey Archived'), ('FILE_DOWNLOADED', 'File Downloaded'), ('MEASUREMENT_CREATED', 'Measurement Created'), ('MEASUREMENT_DELETED', 'Measurement Deleted'), ('ADMIN_ACTION', 'Admin Action')], max_length=50)),
                ('entity_type', models.CharField(db_column='entity_type', max_length=50)),
                ('entity_id', models.IntegerField(db_column='entity_id')),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='ip_address', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='projects.project')),
                ('survey', models.ForeignKey(blank=True, db_column='survey_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity__c2633a_idx'), models.Index(fields=['user'], name='audit_log_user_id_4dac76_idx'), models.Index(fields=['project'], name='audit_log_project_3ba312_idx'), models.Index(fields=['survey'], name='audit_log_survey__0e6d93_idx'), models.Index(fields=['timestamp'], name='audit_log_timesta_e8e14e_idx')],
            },
        ),
    ]
