# Generated by Django 5.2.17 on 2026-08-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=50)),
                ('progress_percent', models.IntegerField(db_column='progress_percent', default=0)),
                ('retry_count', models.IntegerField(db_column='retry_count', default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, related_name='processing_job', to='files.surveyfile')),
            ],
            options={
                'db_table': 'processing_job',
                'indexes': [models.Index(fields=['file'], name='processing__file_id_87e5d8_idx'), models.Index(fields=['status'], name='processing__status_444379_idx'), models.Index(fields=['celery_task_id'], name='processing__celery__ee8928_idx')],
            },
        ),
    ]
