# Generated by Codex on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="dispatch_available_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="dispatch_failure_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="dispatch_last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="dispatch_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="last_heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="lease_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["dispatch_status"], name="processing__dispatc_f87366_idx"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["dispatch_available_at"], name="processing__dispatc_028d11_idx"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["lease_expires_at"], name="processing__lease_e_0c1b9c_idx"),
        ),
    ]
