# Generated by Django 5.2.17 on 2026-08-09 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('TWO_D', '2D'), ('THREE_D', '3D')], max_length=50)),
                ('format', models.CharField(choices=[('GEOTIFF', 'GeoTIFF'), ('TIFF', 'TIFF'), ('PNG', 'PNG'), ('JPEG', 'JPEG'), ('KML', 'KML'), ('GEOJSON', 'GeoJSON'), ('OBJ', 'OBJ'), ('GLB', 'GLB'), ('GLTF', 'GLTF'), ('LAS', 'LAS'), ('LAZ', 'LAZ'), ('PLY', 'PLY'), ('STL', 'STL')], max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256_checksum', models.CharField(max_length=64)),
                ('storage_path', models.CharField(max_length=500)),
                ('preview_path', models.CharField(blank=True, max_length=500, null=True)),
                ('converted_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='uploading', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='surveys.survey')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_file',
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.CharField(db_column='session_id', max_length=255, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('TWO_D', '2D'), ('THREE_D', '3D')], max_length=50)),
                ('total_size_bytes', models.BigIntegerField()),
                ('uploaded_bytes', models.BigIntegerField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('status', models.CharField(default='in_progress', max_length=50)),
                ('checksum_expected', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_session', to='files.surveyfile')),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='surveys.survey')),
            ],
            options={
                'db_table': 'upload_session',
            },
        ),
        migrations.AddIndex(
            model_name='surveyfile',
            index=models.Index(fields=['survey'], name='survey_file_survey__ec175d_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyfile',
            index=models.Index(fields=['status'], name='survey_file_status_fb89a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyfile',
            constraint=models.UniqueConstraint(fields=('sha256_checksum', 'survey'), name='survey_file_unique_checksum_per_survey'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['survey'], name='upload_sess_survey__405dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status'], name='upload_sess_status_5d46ca_idx'),
        ),
    ]
