# Generated by Django 5.2.17 on 2026-08-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyFileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256_checksum', models.CharField(max_length=64)),
                ('storage_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_file', models.ForeignKey(db_column='survey_file_id', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='files.surveyfile')),
            ],
            options={
                'db_table': 'survey_file_asset',
                'indexes': [models.Index(fields=['survey_file'], name='survey_file_survey__9ea2b6_idx'), models.Index(fields=['sha256_checksum'], name='survey_file_sha256__7f6559_idx')],
                'constraints': [models.UniqueConstraint(fields=('survey_file', 'stored_filename'), name='survey_file_asset_unique_name_per_file'), models.UniqueConstraint(fields=('survey_file', 'storage_path'), name='survey_file_asset_unique_path_per_file')],
            },
        ),
    ]
