# Generated by Django 5.2.17 on 2026-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_surveyfileasset'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='surveyfileasset',
            constraint=models.UniqueConstraint(fields=('survey_file', 'sha256_checksum'), name='survey_file_asset_unique_checksum_per_file'),
        ),
    ]
